version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: scripts/wait-for-it.sh -t 120 db:3306 -- scripts/entrypoint
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    links:
      - db
    env_file: .env
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
    env_file: .env
volumes:
  bundle:
